app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

from . import db

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    is_online = db.Column(db.Boolean(), index=True, default=False)

    #for password hashing and verification
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User {}>'.format(self.username)


class Channel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True, unique=True)
    description = db.Column(db.Text())
    is_removable = db.Column(db.Boolean(), index=True, default=True)

    def __repr__(self):
        return '<Channel {}>'.format(self.name)

app/main/forms.py
from flask_wtf import Form
from wtforms.fields import StringField, SubmitField
from wtforms.validators import Required


class EnterRoomForm(Form):
    """Accepts a nickname and a rom name."""
    name = StringField('Name', validators=[Required()])
    room = StringField('Room', validators=[Required()])
    submit = SubmitField('Enter Chatroom')

app/__init__.py
from flask import Flask
from flask_socketio import SocketIO
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

from .. import config

socketio = SocketIO()
db = SQLAlchemy()


def create_app():
    """Create an application."""

    app = Flask(__name__, instance_relative_config=False)
    app.config.from_object(config.ConfigDev)

    # Login Manager
    login = LoginManager()
    # default login view
    login.login_view = 'auth.login'

    # Initialize Plugins
    login.init_app(app)
    db.init_app(app)

    # DB migration
    Migrate(app, db)

    # Import the models
    from . import models

    #  User loader function, that can be called to load a user given the ID
    @login.user_loader
    def load_user(id):
        return models.User.query.get(int(id))


    # Use blueprint to organize the project in
    # differents apps
    from .main import main as main_blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint)

    socketio.init_app(app)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, events

app/main/routes.py
from flask import session, redirect, url_for, render_template, request, flash
from flask_login import current_user, login_required

from ..models import User, Channel
from .. import db
from . import main
from .forms import EnterRoomForm

import json

@main.route('/', methods=['GET', 'POST'])
@login_required
def index():
    """Login form to enter a room."""

    # statics predefined rooms
    rooms = []
    room1 = {'name': 'room-1', 'description': 'This is the Generale room'}
    room2 = {'name': 'room-2', 'description': 'This is the Second room'}
    room3 = {'name': 'room-3', 'description': 'This is the Third room'}

    customs_channels = Channel.query.filter_by(is_removable=True)
    customs_rooms = [{'name': channel.name, 'description': channel.description}\
    for channel in customs_channels]

    rooms = [room1, room2, room3]

    return render_template('index.html', rooms=rooms,
                           customs_rooms=customs_rooms)


@main.route('/chat')
@login_required
def chat():
    """Chat room. The user's name and room must be stored in
    the session."""
    name = session.get('username', '')
    room = session.get('room', '')
    if name == '' or room == '':
        return redirect(url_for('.index'))
    return render_template('chat.html', name=name, room=room)


@main.route('/join/<username>/<room>')
@login_required
def join_room(username, room):
    # Set the sessions variables
    session['username'] = username
    session['room'] = room
    # Redirect the user to the chat room
    return redirect(url_for('.chat'))


@main.route('/profile/<username>')
@login_required
def profile(username):
    return render_template('profile.html', username=username)


@main.route('/connected_users', methods=['GET'])
def connected_user():
    users_online = User.query.filter_by(is_online=True)
    users_online = users_online.filter(User.email!=current_user.email)

    users_online = [{'username': user.username, 'email': user.email}\
    for user in users_online]

    return json.dumps({'connected_users': users_online})


@main.route('/private_chat/<send_to>')
@login_required
def join_private_chat(send_to):
    """View for private send private message to a user"""
    session['send_to'] = send_to
    session['sender'] = current_user.username
    return redirect(url_for('.private_chat'))


@main.route('/private_chat')
@login_required
def private_chat():
    send_to = session.get('send_to')
    # sender = session.get('sender')
    return render_template('private_chat.html', send_to=send_to)


@main.route('/create_channel', methods=['POST', 'GET'])
@login_required
def create_channel():
    """ Register a user """
    # Form is filled then we send it via POST
    if request.method == 'POST':
        name = request.form.get('name')
        description = request.form.get('description')

        channel = Channel.query.filter_by(name=name).first()
        # If a channel is found, redirect back to create page so user can try again
        if channel:
            flash('Channel already exists')
            return redirect(url_for('.create_channel'))

        # Create new channel with the form data.
        new_channel = Channel(name=name, description=description)

        # add the new channel to the database
        db.session.add(new_channel)
        db.session.commit()

        return redirect(url_for('.index'))

    # Show the create channel page
    return render_template('create_channel.html')

app/templates/base.html
<!-- templates/base.html -->

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Flask-SocketIO-Chat {% endblock %}</title>
    <!-- SocketIo Js Client -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js" integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/f838e3983e.js" crossorigin="anonymous"></script>
    <!-- Bulma css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <!-- Additionals css -->
    {% block style %}
    {% endblock %}
</head>

<body>
    <section class="hero is-primary is-fullheight">
        {% block nav %}
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.index') }}" class="navbar-item">
                                Home
                            </a>

                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>

                            <a href="{{url_for('main.profile', username=current_user.username)}}" class="navbar-item">
                                Profile
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        {% endblock %}

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>

    <!-- Customs Js scripts -->
    {% block scripts %}
    {% endblock %}
</body>

</html>

app/templates/chat.html
{% extends "base.html" %}


{% block title %}
Right-Chat: {{ room }}
{% endblock %}

<!-- Script for this template -->
{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/private_chat.css')}}">
{% endblock %}

<!-- No navbar here -->
{% block nav %}
{% endblock %}

{% block content %}
<div class="column is-8 is-offset-3">
    <h1>Flask-SocketIO-Chat: {{ room }}</h1>

    <section id="speech-box">

    </section>

    <!-- <textarea id="chat" rows="20"></textarea><br><br> -->
    <div class="field" id="message-field">
        <p class="control has-icons-left">
            <input class="input is-rounded" id="text" type="text" placeholder="Enter your message here">
            <span class="icon is-left">
              <i class="fas fa-paper-plane"></i>
            </span>
        </p>
    </div>
    <a href="#" class="leave">Leave this room</a>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/chat.js') }}"></script>
{% endblock %}

app/templates/create_channel.html
<!-- templates/auth/signup.html -->

{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Create a Channel</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="{{ url_for('.create_channel') }}">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control is-medium">
                    <textarea class="textarea has-fixed-size" name="description" placeholder="Channel description"></textarea>
                </div>
            </div>

            <div class="field is-grouped">
                <div class="control">
                    <button class="button is-info" type="submit">Save</button>
                </div>
                <div class="control">
                    <a href="{{ url_for('.index') }}">
                        <input type="button" class="button is-danger" value="Cancel">
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/index.html
<!-- templates/index.html -->

{% extends "base.html" %}

{% block content %}
<!-- List of predefined Channels -->
<div class="columns">
    <div class="column is 5">
        <h2 class="title">Channels </h2>
        {% for room in rooms %}
        <div class="box ">
            <a href="{{ url_for('main.join_room',username=current_user.username, room=room.name) }}">
                <article class="media" id="{{ room.name }}">
                    <div class="media-left">
                      <figure class="image is-64x64">
                        <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
                      </figure>
                    </div>
                    <div class="media-content">
                      <div class="content">
                        <p>
                          <strong>{{ room.name }}</strong> <small>@{{ room.name }}</small> <small>31m</small>
                          <br>
                          {{ room.description }}
                        </p>
                      </div>
                    </div>
                </article>
            </a>
        </div>
        {% endfor %}
        <h2 class="title">Customs Channels</h2>
        {% for room in customs_rooms %}
        <div class="box ">
            <a href="{{ url_for('main.join_room',username=current_user.username, room=room.name) }}">
                <article class="media" id="{{ room.name }}">
                    <div class="media-left">
                      <figure class="image is-64x64">
                        <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
                      </figure>
                    </div>
                    <div class="media-content">
                      <div class="content">
                        <p>
                          <strong>{{ room.name }}</strong> <small>@{{ room.name }}</small> <small>31m</small>
                          <br>
                          {{ room.description }}
                        </p>
                      </div>
                    </div>
                </article>
            </a>
        </div>
        <br/>
        {% endfor %}
        <a href="{{ url_for('.create_channel') }}">
          <button class="button is-medium is-info is-fullwidth is-rounded" id="new-channel">
              <span class="icon is-medium">
                  <i class="fas fa-plus"></i>
              </span>
              <span>New channel</span>
          </button>
        </a>
    </div>

    <!-- Connected users list -->
    <div class="column is-5 is-offset-2" id="connected_users">
        <h2 class="title">Peoples</h2>

        <div id="users-box">
        </div>

        <button class="button is-medium is-info is-fullwidth" id="update-btn">
            Update list
        </button>
    </div>
</div>

{% endblock %}

<!-- Ajax call for update connected users list -->
{% block scripts %}
<!-- jQuery core -->
<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js">
</script>

<!-- jQuery ajax call scripts -->
<script type="text/javascript" src="{{ url_for('static', filename='js/index.js') }}"></script>
{% endblock %}

app/templates/private_chat.html
{% extends "base.html" %}


{% block title %}
Right-Chat: {{ room }}
{% endblock %}

<!-- Script for this template -->
{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/private_chat.css')}}">
{% endblock %}

<!-- No navbar here -->
{% block nav %}
{% endblock %}

{% block content %}
<div class="column is-8 is-offset-3">
    <h1>Your conversation with : {{ send_to }}</h1>

    <section id="speech-box">

    </section>
    <!--
    <textarea id="chat" rows="10"></textarea><br><br>
    -->
    <div class="field">
        <p class="control has-icons-left">
            <input class="input is-rounded" id="text" type="text" placeholder="Enter your message here">
            <span class="icon is-left">
              <i class="fas fa-paper-plane"></i>
            </span>
        </p>
    </div>
    <a href="#" class="leave">Leave conversation</a>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/private_chat.js') }}"></script>
{% endblock %}

app/templates/profile.html
<!-- templates/profile.html -->

{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome, {{ username }}!
</h1>
{% endblock %}